# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a0241485646210ed6f839a06413ce4cf9eae512aae9aa17580766ea5bcb876cc643bb606c2ecf9a74a8158b9061c18e8f0f79bd02ea1476010b904c99c216ef

test:
  secret_key_base: 9c2716fd0bb7d13ec7021454ca392c31290dd96f0cf795c528dd4305c3b1721b8acae73c826bbfd91996961071687e6a5fa67fe2bef63a1e1b0d8b5a2550b3d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
