# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 394c0c9dbe976f3794fe44663abca75572fe2f32a705ef1955a34ee1ea3de0215cd5fa601da18e2a94c93403239f048c5fb3cd6616f1be3cfa8d130c6386f590

test:
  secret_key_base: 075694393d5be0fcd49795c86cf4072f0e99b94a64d9e5c38b529c69eb6cdc33b10c8f15d343fe0cf93c89bd4d9d68c7c9f8fe32e1a77bf09778e413f05a0de3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
