# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b1af3769c723cf66d3dafff10d776d065ae9baf40e32d76be3e4d3d8343beb693273c37406283f9afa78dae130f3f3ca4e2d86866359906d088eba12b3ba399

test:
  secret_key_base: d157e0c7322448282424c96acb7ffd5e5b996d89b443b5d7a0447262b9a17b5e8354ba4e2e5469b91a4e89de9607f31298752170a66c7bd36a25076236cf7f27

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
